spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:9000/system
    username: root
    password: root
  jpa:
    show-sql: false
    generate-ddl: false
    database: MYSQL
    properties:
      hibernate.generate_statistics: false
      hibernate.format_sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    cloud:
      stream:
        kafka:
          binder:
            brokers: localhost:9092
          streams:
            binder:
              configuration:
                default:
                  key:
                    serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                  value:
                    serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            bindings:
              requests-in:
                consumer:
                  application-id: custom-listener
                  .: raw
        bindings:
          requests-in:
            destination: events
            header-mode: raw

mpp:
  elasticsearch:
    url: "http://localhost:9200"
