spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:9000/system
    username: root
    password: root
  jpa:
    show-sql: false
    generate-ddl: false
    database: MYSQL
    properties:
      hibernate.generate_statistics: false
      hibernate.format_sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks: "all"
      retries: 0
      batch-size: 100
      linger:
        ms: 1
      buffer:
        memory: 3355443
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: wallet
      auto-offset-reset: earliest
      enable:
        auto:
          commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
mpp:
  elasticsearch:
    url: "http://localhost:9200"
